In [1]:
import pandas as pd
import os
import subprocess
import numpy as np

In [2]:
meta = pd.read_csv('../../data/AnimalDatasetV2Original/Meta For Animal Dataset Ver.2.csv',dtype={'Image No.':'str'})

In [3]:
meta.drop(['Unnamed: 9'],axis=1,inplace=True)

In [4]:
meta.head()

,Patient No.,Species,Breed,Age (yrs),Gender,Neuter,Image Findings,Thoracic or Pelvic,Image No.
0,1,Canine,German Shepherd,2,Female,Yes,Osteochondrosis with Osteophytes,Thoracic,001
1,1,Canine,German Shepherd,2,Female,Yes,Osteochondrosis with Osteophytes,Thoracic,002
2,1,Canine,German Shepherd,2,Female,Yes,Osteochondrosis with Osteophytes,Thoracic,003
3,1,Canine,German Shepherd,2,Female,Yes,Osteochondrosis with Osteophytes,Thoracic,004
4,1,Canine,German Shepherd,2,Female,Yes,Osteochondrosis with Osteophytes,Thoracic,005

In [5]:
meta['Normal_Abnormal'] = meta['Image Findings'] == 'Normal'

In [6]:
meta.loc[meta['Normal_Abnormal']==True]

,Patient No.,Species,Breed,Age (yrs),Gender,Neuter,Image Findings,Thoracic or Pelvic,Image No.,Normal_Abnormal
15,4,Canine,Kelpie,2,Unknown,Unknown,Normal,Pelvic,016,True
16,4,Canine,Kelpie,2,Unknown,Unknown,Normal,Pelvic,017,True
17,4,Canine,Kelpie,2,Unknown,Unknown,Normal,Pelvic,018,True
18,4,Canine,Kelpie,2,Unknown,Unknown,Normal,Pelvic,019,True
27,7,Canine,Great Dane,0.19,Male,No,Normal,Thoracic,028,True
...,...,...,...,...,...,...,...,...,...,...
492,139,Canine,Terrier Mix,4.5,Male,Unknown,Normal,Thoracic,493,True
493,139,Canine,Terrier Mix,4.5,Male,Unknown,Normal,Thoracic,494,True
494,139,Canine,Terrier Mix,4.5,Male,Unknown,Normal,Thoracic,495,True
497,141,Feline,DSH,8,Male,Yes,Normal,Pelvic,498,True
499,141,Feline,DSH,8,Male,Yes,Normal,Pelvic,500,True

In [7]:
dataset = meta.drop(['Patient No.','Species','Breed',
           'Age (yrs)','Gender','Neuter',
           'Image Findings','Thoracic or Pelvic'],
          axis=1
         )

In [8]:
dataset['cv']=0

In [9]:
dataset.head()

  Image No.  Normal_Abnormal  cv
0       001            False   0
1       002            False   0
2       003            False   0
3       004            False   0
4       005            False   0

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(dataset['Image No.'],
                                                    dataset['Normal_Abnormal'],
                                                    test_size = 0.2,
                                                    random_state = 42,
                                                    stratify = dataset['Normal_Abnormal']
                                                   )
print(len(X_test))
print(len(X_train))
for i in X_test:
    dataset.loc[dataset['Image No.']==i,'cv'] = 1

100
400

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X_train,
                                                    y_train,
                                                    test_size = 100/len(X_train),
                                                    random_state = 42,
                                                    stratify = y_train
                                                   )
print(len(X_test))
print(len(X_train))
for i in X_test:
    dataset.loc[dataset['Image No.']==i,'cv'] = 2

100
300

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X_train,
                                                    y_train,
                                                    test_size = 100/len(X_train),
                                                    random_state = 42,
                                                    stratify = y_train
                                                   )
print(len(X_test))
print(len(X_train))
for i in X_test:
    dataset.loc[dataset['Image No.']==i,'cv'] = 3

100
200

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X_train,
                                                    y_train,
                                                    test_size = 100/len(X_train),
                                                    random_state = 42,
                                                    stratify = y_train
                                                   )
print(len(X_test))
print(len(X_train))
for i in X_test:
    dataset.loc[dataset['Image No.']==i,'cv'] = 4
for i in X_train:
    dataset.loc[dataset['Image No.']==i,'cv'] = 5

100
100

In [15]:
# X_train, X_test, y_train, y_test = train_test_split(X_train,
#                                                     y_train,
#                                                     test_size = 100/len(X_train),
#                                                     random_state = 42,
#                                                     stratify = y_train
#                                                    )
# print(len(X_test))
# print(len(X_train))
# for i in X_test:
#     dataset.loc[dataset['Image No.']==i,'cv'] = 5

In [16]:
dataset[dataset['cv']==1].groupby(dataset['Normal_Abnormal']).count()

                 Image No.  Normal_Abnormal  cv
Normal_Abnormal
False                   71               71  71
True                    29               29  29

In [17]:
dataset[dataset['cv']==2].groupby(dataset['Normal_Abnormal']).count()

                 Image No.  Normal_Abnormal  cv
Normal_Abnormal
False                   71               71  71
True                    29               29  29

In [18]:
dataset[dataset['cv']==3].groupby(dataset['Normal_Abnormal']).count()

                 Image No.  Normal_Abnormal  cv
Normal_Abnormal
False                   71               71  71
True                    29               29  29

In [19]:
dataset[dataset['cv']==4].groupby(dataset['Normal_Abnormal']).count()

                 Image No.  Normal_Abnormal  cv
Normal_Abnormal
False                   72               72  72
True                    28               28  28

In [20]:
dataset[dataset['cv']==5].groupby(dataset['Normal_Abnormal']).count()

                 Image No.  Normal_Abnormal  cv
Normal_Abnormal
False                   71               71  71
True                    29               29  29

In [21]:
def run_bash(command):
    process = subprocess.Popen(command.split(),stdout=subprocess.PIPE)
    output,error = process.communicate()
    return output,error

In [22]:
dataset.head(n=20)

   Image No.  Normal_Abnormal  cv
0        001            False   4
1        002            False   1
2        003            False   3
3        004            False   3
4        005            False   4
5        006            False   4
6        007            False   2
7        008            False   2
8        009            False   4
9        010            False   5
10       011            False   4
11       012            False   2
12       013            False   2
13       014            False   1
14       015            False   2
15       016             True   5
16       017             True   3
17       018             True   4
18       019             True   4
19       020            False   5

In [23]:
normals = 0
abnormals = 0
for i,r in dataset.iterrows():
    if r['Normal_Abnormal']:
        normals += 1
        command = 'cp ' + '../../data/AnimalDatasetV2Original/' + r['Image No.'] + '.jpg ' + '../../data/AnimalDatasetV2CVs/CV' + str(r['cv']) + '/test/normal/'
        output,error = run_bash(command)
    else:
        abnormals += 1
        command = 'cp ' + '../../data/AnimalDatasetV2Original/' + r['Image No.'] + '.jpg ' + '../../data/AnimalDatasetV2CVs/CV' + str(r['cv']) + '/test/abnormal/'
        output,error = run_bash(command)

In [24]:
for cv in np.arange(1,5+1):
    tmp_set = dataset[dataset['cv']!=cv]
    print(len(tmp_set))
    for i,r in tmp_set.iterrows():
        if r['Normal_Abnormal']:
            command = 'cp ' + '../../data/AnimalDatasetV2Original/' + r['Image No.'] + '.jpg ' + '../../data/AnimalDatasetV2CVs/CV' + str(cv) + '/train/normal/'
            output,error = run_bash(command)
        else:
            command = 'cp ' + '../../data/AnimalDatasetV2Original/' + r['Image No.'] + '.jpg ' + '../../data/AnimalDatasetV2CVs/CV' + str(cv) + '/train/abnormal/'
            output,error = run_bash(command)

400
400
400
400
400

In [25]:
dataset[dataset['cv']!=1]

    Image No.  Normal_Abnormal  cv
0         001            False   4
2         003            False   3
3         004            False   3
4         005            False   4
5         006            False   4
..        ...              ...  ..
492       493             True   4
494       495             True   5
496       497            False   5
497       498             True   4
499       500             True   3

[400 rows x 3 columns]

In [27]:
meta['Test_CV'] = dataset['cv']

In [28]:
meta

,Patient No.,Species,Breed,Age (yrs),Gender,Neuter,Image Findings,Thoracic or Pelvic,Image No.,Normal_Abnormal,Test_CV
0,1,Canine,German Shepherd,2,Female,Yes,Osteochondrosis with Osteophytes,Thoracic,001,False,4
1,1,Canine,German Shepherd,2,Female,Yes,Osteochondrosis with Osteophytes,Thoracic,002,False,1
2,1,Canine,German Shepherd,2,Female,Yes,Osteochondrosis with Osteophytes,Thoracic,003,False,3
3,1,Canine,German Shepherd,2,Female,Yes,Osteochondrosis with Osteophytes,Thoracic,004,False,3
4,1,Canine,German Shepherd,2,Female,Yes,Osteochondrosis with Osteophytes,Thoracic,005,False,4
...,...,...,...,...,...,...,...,...,...,...,...
495,140,Feline,DSH,14,Male,Unknown,Osteosarcoma,Thoracic,496,False,1
496,140,Feline,DSH,14,Male,Unknown,Osteosarcoma,Thoracic,497,False,5
497,141,Feline,DSH,8,Male,Yes,Normal,Pelvic,498,True,4
498,141,Feline,DSH,8,Male,Yes,DJD,Pelvic,499,False,1
499,141,Feline,DSH,8,Male,Yes,Normal,Pelvic,500,True,3

In [29]:
meta.to_csv('./meta.csv',
            index=None,
            encoding='utf-8',
           )

In [30]:
meta2 = pd.read_csv('./meta.csv')
meta2.head()

,Patient No.,Species,Breed,Age (yrs),Gender,Neuter,Image Findings,Thoracic or Pelvic,Image No.,Normal_Abnormal,Test_CV
0,1,Canine,German Shepherd,2,Female,Yes,Osteochondrosis with Osteophytes,Thoracic,1,False,4
1,1,Canine,German Shepherd,2,Female,Yes,Osteochondrosis with Osteophytes,Thoracic,2,False,1
2,1,Canine,German Shepherd,2,Female,Yes,Osteochondrosis with Osteophytes,Thoracic,3,False,3
3,1,Canine,German Shepherd,2,Female,Yes,Osteochondrosis with Osteophytes,Thoracic,4,False,3
4,1,Canine,German Shepherd,2,Female,Yes,Osteochondrosis with Osteophytes,Thoracic,5,False,4

In [31]:
meta2.groupby(meta2['Image Findings']).count()

,Patient No.,Species,Breed,Age (yrs),Gender,Neuter,Thoracic or Pelvic,Image No.,Normal_Abnormal,Test_CV
Image Findings,,,,,,,,,,
Angular Limb Deformity,2,2,2,2,2,2,2,2,2,2
Avascular Necrosis,2,2,2,2,2,2,2,2,2,2
Avulsion,9,9,9,9,9,9,9,9,9,9
Bone Cyst,2,2,2,2,2,2,2,2,2,2
Bone Lysis,5,5,5,5,5,5,5,5,5,5
Bone Lysis due to Multiple Myeloma,4,4,4,4,4,4,4,4,4,4
Bone Lysis due to Mycosis,11,11,11,11,11,11,11,11,11,11
Bone Lysis due to Osteomyelitis,3,3,3,3,3,3,3,3,3,3
Cortical Destruction and Periosteal Proliferation,4,4,4,4,4,4,4,4,4,4
DJD,29,29,29,29,29,29,29,29,29,29
DJD associated Femoral Head Osteotomy,1,1,1,1,1,1,1,1,1,1
Deformity,5,5,5,5,5,5,5,5,5,5
Deformity and Elbow Dysplasia,2,2,2,2,2,2,2,2,2,2
Ectrodactyly,6,6,6,6,6,6,6,6,6,6
Elbow Dysplasia,14,14,14,14,14,14,14,14,14,14
Elbow incongruity,6,6,6,6,6,6,6,6,6,6
Fracture,40,40,40,40,40,40,40,40,40,40
Fracture Due to Gun Shot,4,4,4,4,4,4,4,4,4,4
Fragment,4,4,4,4,4,4,4,4,4,4
Hypertrophic Osteodystrophy,18,18,18,18,18,18,18,18,18,18
Hypertrophic Osteopathy,2,2,2,2,2,2,2,2,2,2
Implant,29,29,29,29,29,29,29,29,29,29
Lucency In Bone,3,3,3,3,3,3,3,3,3,3
Luxation,8,8,8,8,8,8,8,8,8,8
Metastatic Osteosarcoma,2,2,2,2,2,2,2,2,2,2
Metastatic Sarcoma,2,2,2,2,2,2,2,2,2,2
Mixed Bone Production and Destruction,3,3,3,3,3,3,3,3,3,3
Mixed Bone Production and Destruction and DJD,1,1,1,1,1,1,1,1,1,1
Mixed Osteolysis and Osteoproduction,1,1,1,1,1,1,1,1,1,1
Multiple Myeloma,1,1,1,1,1,1,1,1,1,1
Normal,144,144,144,144,144,144,144,144,144,144
Osteoarthrosis,7,7,7,7,7,7,7,7,7,7
Osteochondritis Dissecans,10,10,10,10,10,10,10,10,10,10
Osteochondrosis,17,17,17,17,17,17,17,17,17,17
Osteochondrosis with Osteophytes,5,5,5,5,5,5,5,5,5,5
Osteochrondroma,2,2,2,2,2,2,2,2,2,2
Osteolysis,11,11,11,11,11,11,11,11,11,11
Osteolysis Due to Metastasis,5,5,5,5,5,5,5,5,5,5
Osteolysis Due to Synovial Sarcoma,3,3,3,3,3,3,3,3,3,3
Osteolysis and pathologic fracture,1,1,1,1,1,1,1,1,1,1
Osteophytes,3,3,3,3,3,3,3,3,3,3
Osteosarcoma,11,11,11,11,11,11,11,11,11,11
Osteosarcoma and DJD of Coxofemoral,2,2,2,2,2,2,2,2,2,2
Osteosarcoma and Pathologic Fracture,1,1,1,1,1,1,1,1,1,1
Osteymyelitis,3,3,3,3,3,3,3,3,3,3
Panosteitis,1,1,1,1,1,1,1,1,1,1
Patella Luxation,4,4,4,4,4,4,4,4,4,4
Pathologic Fracture,6,6,6,6,6,6,6,6,6,6
Pathologic Fracture and Distorsion,1,1,1,1,1,1,1,1,1,1
Periosteal Reaction,1,1,1,1,1,1,1,1,1,1
Radial Hypoplasia,4,4,4,4,4,4,4,4,4,4
Retained Cartilage Core,6,6,6,6,6,6,6,6,6,6
Rough Lateral Femoral Condyle,1,1,1,1,1,1,1,1,1,1
Soft Tissue Mass,3,3,3,3,3,3,3,3,3,3
Soft Tissue Swelling,17,17,17,17,17,17,17,17,17,17
Subluxation,6,6,6,6,6,6,6,6,6,6
Thickened Patella Ligament,2,2,2,2,2,2,2,2,2,2